FROM maven:3.8.2-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/Placement-Assistant-0.0.1-SNAPSHOT.jar Placement-Assistant.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","Placement-Assistant.jar"]
